[debug]: 2019-06-28T15:54:00.811Z 	Testing INFO log. {"test1":"hello","test2":"goodbye"}
[debug]: 2019-06-28T15:54:34.712Z 	Testing INFO log. undefined
[debug]: 2019-06-28T15:54:45.372Z 	Testing INFO log. {"test1":"hello","test2":"goodbye"}
[debug]: 2019-06-28T15:55:22.828Z 	Testing INFO log. {"test1":"hello","test2":"goodbye"}
[error]: 2019-06-28T15:57:18.779Z 	uncaughtException: Delibertly thrown Exception for testing
Error: Delibertly thrown Exception for testing
    at Object.<anonymous> (/Users/mike/Sites/Personal/nodejs-complete-guide-restful-apis/vidly/index.js:55:7)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3) undefined
[error]: 2019-06-28T15:57:18.782Z 	Delibertly thrown Exception for testing undefined
[error]: 2019-06-28T15:58:37.042Z 	uncaughtException: Delibertly thrown Exception for testing
Error: Delibertly thrown Exception for testing
    at Object.<anonymous> (/Users/mike/Sites/Personal/nodejs-complete-guide-restful-apis/vidly/index.js:55:7)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3) undefined
[error]: 2019-06-28T15:58:37.044Z 	Delibertly thrown Exception for testing undefined
[error]: 2019-06-28T15:58:54.355Z 	uncaughtException: Delibertly thrown Exception for testing
Error: Delibertly thrown Exception for testing
    at Object.<anonymous> (/Users/mike/Sites/Personal/nodejs-complete-guide-restful-apis/vidly/index.js:55:7)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3) undefined
[error]: 2019-06-28T15:58:54.358Z 	Delibertly thrown Exception for testing undefined
